include:
  - project: "repos/cloud/cicd/gitlab-ci"
    file: "py3.9-bullseye-tox/gitlab-ci.yaml"
  - project: "repos/cloud/cicd/gitlab-ci"
    file: "toolforge-cd/only_image_publish.yaml"
  - project: "repos/cloud/cicd/gitlab-ci"
    file: "toolforge-cd/only_helm_publish.yaml"

variables:
  PROJECT_NAME: jobs-api
