default_language_version:
  python: python3

repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
        files: \.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        exclude: ^tests/
        verbose: true
        args: [--show-error-codes, --strict]
        additional_dependencies:
          [
            "pydantic",
            "toolforge-weld",
            "types-PyYAML",
            "fastapi",
            "types-requests",
            "types-setuptools",
            "prometheus-client",
            "prometheus-fastapi-instrumentator",
            "requests-mock",
            "websockets",
          ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-merge-conflict

  - repo: https://github.com/python-openapi/openapi-spec-validator
    rev: 0.8.0b1
    hooks:
      - id: openapi-spec-validator

  - repo: https://gitlab.wikimedia.org/repos/cloud/cicd/gitlab-ci
    rev: 10a6d2120841adaa2dfc6857c82bb59b5538eacb
    hooks:
      - id: check-openapi-version-bump
