[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "tjf"
version = "0.0.1"
description = ""
authors = ["Taavi Väänänen <hi@taavi.wtf>"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.0"
flask-restful = "^0.3.10"
prometheus-flask-exporter = "^0.23.0"
pyyaml = "^6.0.1"
requests = "^2.31.0"
cryptography = "^41.0.7"
toolforge-weld = "^1.4.0"
gunicorn = "^21.2.0"

[tool.black]
line-length = 99
target_version = ['py39']

[tool.isort]
profile = "black"
skip_gitignore = true
