# base values file
replicas: 2

webservice:
  image:
    repository: docker-registry.tools.wmflabs.org/toolforge-jobs-framework-api
    tag: OVERWRITTEN_BY_CI
    pullpolicy: Always
nginx:
  image:
    repository: docker-registry.tools.wmflabs.org/nginx
    # tag is used by the ci to set the image tag
    nginxTag: latest
    pullpolicy: Always

certificates:
  apiGatewayCa:
    name: api-gateway-backend-ca
    kind: ClusterIssuer
    group: cert-manager.io
